version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - src/:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=ecommerce
      - DB_USER=root
      - DB_PASSWORD=password

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
